services:
  worker:
    build: ./worker
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy
